name: Build and Push Docker Image

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
    # Only trigger if pom.xml or Dockerfile changes
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - 'src/**'  # Optional: include changes in the source code

  # Also trigger on pull requests targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - 'src/**'  # Optional: include changes in the source code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-java-app:latest .
        
    # Push the Docker image to ACR
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-java-app:latest
