name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}  # usecasecr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}  # Your ACR username (service principal client ID)
          password: ${{ secrets.AZURE_ACR_PASSWORD }}  # Your ACR password (service principal client secret)

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-java-app:latest .

      # Push the Docker image to Azure Container Registry
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-java-app:latest
